kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment:
      TOKEN:
        from_secret: gitea
      TOKEN_DOCKER:
        from_secret: docker_hub
    commands:
      - dockerd &
      - docker login -u kieran -p $TOKEN git.v0l.io
      - docker login -u voidic -p $TOKEN_DOCKER
      - docker buildx build --push -t git.v0l.io/kieran/void-cat-rs:latest t voidic/void-cat-rs:latest .
      - kill $(cat /var/run/docker.pid)