[package]
name = "route96"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "void_cat_migrate"
required-features = ["bin-void-cat-migrate"]

[[bin]]
name = "route96"
path = "src/bin/main.rs"

[lib]
name = "route96"

[features]
default = ["nip96", "blossom"]
labels = ["nip96", "dep:candle-core", "dep:candle-nn", "dep:candle-transformers"]
nip96 = ["dep:ffmpeg-sys-the-third", "dep:blurhash", "dep:libc"]
blossom = []
bin-void-cat-migrate = ["dep:sqlx-postgres", "dep:clap", "dep:clap_derive"]

[dependencies]
log = "0.4.21"
nostr = "0.34.1"
pretty_env_logger = "0.5.0"
rocket = { version = "0.5.0", features = ["json"] }
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros"] }
base64 = "0.22.1"
hex = "0.4.3"
serde = { version = "1.0.198", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4"] }
anyhow = "1.0.82"
sha2 = "0.10.8"
sqlx = { version = "0.8.1", features = ["mysql", "runtime-tokio", "chrono", "uuid"] }
config = { version = "0.14.0", features = ["toml"] }
chrono = { version = "0.4.38", features = ["serde"] }
url = "2.5.0"
serde_with = { version = "3.8.1", features = ["hex"] }
ureq = { version = "2.9.7", features = ["json"] }

libc = { version = "0.2.153", optional = true }
blurhash = { version = "0.2.1", optional = true }
ffmpeg-sys-the-third = { version = "2.0.0", features = ["default"], optional = true }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "^0.6.1", optional = true }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "^0.6.1", optional = true }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "^0.6.1", optional = true }
clap = { version = "4.5.18", features = ["derive"], optional = true }
sqlx-postgres = { version = "0.8.2", optional = true, features = ["chrono", "uuid"] }
clap_derive = { version = "4.5.18", optional = true }

