# Listen address for webserver
listen = "0.0.0.0:8000"

# Database connection string (MYSQL)
database = "mysql://root:root@db:3306/void_cat"

# Directory to store uploads
storage_dir = "/app/data"

# Maximum support filesize for uploading
max_upload_bytes = 104857600

# Public facing url
public_url = "http://localhost:8000"

# Whitelisted pubkeys, leave out to disable
# whitelist = ["63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed"]