# Listen address for webserver
listen: "127.0.0.1:8000"

# Database connection string (MYSQL)
database: "mysql://root:root@localhost:3366/route96"

# Directory to store uploads
storage_dir: "./data"

# Maximum support filesize for uploading
max_upload_bytes: 5e+9

# Public facing url
public_url: "http://localhost:8000"

# Whitelisted pubkeys, leave out to disable
# whitelist: ["63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed"]

# Path for ViT(224) image model (https://huggingface.co/google/vit-base-patch16-224)
vit_model:
  model: "/home/kieran/Downloads/falcon_nsfw.safetensors"
  config: "/home/kieran/Downloads/falcon_nsfw.json"

# Webhook api endpoint
# webhook_url: "https://api.snort.social/api/v1/media/webhook"

# Analytics support
# plausible_url: "https://plausible.com/"

# Support legacy void
# void_cat_database: "postgres://postgres:postgres@localhost:41911/void"