# Listen address for webserver
listen = "127.0.0.1:8000"

# Database connection string (MYSQL)
database = "mysql://root:root@localhost:3366/void_cat"

# Directory to store uploads
storage_dir = "./data"

# Maximum support filesize for uploading
max_upload_bytes = 5e+9

# Public facing url
public_url = "http://localhost:8000"

# Whitelisted pubkeys, leave out to disable
# whitelist = ["63fe6318dc58583cfe16810f86dd09e18bfd76aabc24a0081ce2856f330504ed"]

# Path for ViT(224) image model (https://huggingface.co/google/vit-base-patch16-224)
# vit_model_path = "model.safetennsors"

# Webhook api endpoint
webhook_url = "https://api.snort.social/api/v1/media/webhook"