volumes:
  db:
  files:
services:
  db:
    image: mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=root"
      - "MARIADB_DATABASE=route96"
    volumes:
      - "db:/var/lib/mysql"
  app:
    image: voidic/route96
    #build: .
    environment:
      - "RUST_LOG=info"
    ports:
      - "8000:8000"
    volumes:
      - "files:/app/data"
      - "./config.prod.yaml:/app/config.yaml"
